- name: Ensure group "kubernetes" exists
  group:
    name: kubernetes
    state: present

- name: Create kubernetess user
  user:
   name: kubernetes
   state: present
   groups:
     - kubernetes
   shell: /bin/nologin
   system: yes
   createhome: no

- name: Deploy Kubernetes Admin kubeconfig
  copy: src=../../../../Konfiguration/{{ clusterName }}/master-admin.kubeconfig dest=/opt/kubernetes/config/ owner=kubernetes group=kubernetes mode=0600
