- include: worker-tools.yml
- include: worker-docker.yml
- include: worker-user.yml
- include: worker-directory-structure.yml
- include: worker-certs.yml
- include: worker-kubelet.yml
- include: worker-kube-proxy.yml